installer:
  release: "v0.4.6"
  image: "quay.io/devtron/inception"
  tag: "acb623ff-185-7117"
  
components:
  dashboard:
    image: "quay.io/devtron/dashboard:c8b8d431-240-8868"
  devtron:
    image: "quay.io/devtron/hyperion:35702e69-280-8870"
  argocdDexServer:
    image: "quay.io/dexidp/dex:v2.25.0"
  kubelink:
    image: "quay.io/devtron/kubelink:d691bfbb-318-8695"
  postgres:
    image: "quay.io/devtron/postgres:11.9.0-debian-10-r26"
  
  migrator:
    image: "quay.io/devtron/migrator:6687f572-133-2208"
    envVars:
      devtron:
        GIT_BRANCH: "main"
        GIT_HASH: "35702e690d6ffb8e61904de33a7f98082cbd2db2"
      casbin:
        GIT_BRANCH: "main"
        GIT_HASH: "35702e690d6ffb8e61904de33a7f98082cbd2db2"
