installer:
  release: "v0.4.20"
  image: "quay.io/devtron/inception"
  tag: "c62d4c30-185-9354"
  
components:
  dashboard:
    image: "quay.io/devtron/dashboard:ec14e17c-325-9470"
  devtron:
    image: "quay.io/devtron/hyperion:a99c738b-280-9460"
    cicdImage: "quay.io/devtron/devtron:a99c738b-326-9459"
  argocdDexServer:
    image: "quay.io/dexidp/dex:v2.25.0"
    initContainer:
      authenticator: "quay.io/devtron/authenticator:415f5470-279-6520"
      cicdAuthenticator: "quay.io/argoproj/argocd:v1.8.1"
  kubelink:
    image: "quay.io/devtron/kubelink:59a0df88-318-9226"
  postgres:
    image: "quay.io/devtron/postgres:11.9.0-debian-10-r26"
  
  migrator:
    image: "quay.io/devtron/migrator:6687f572-133-2208"
    envVars:
      devtron:
        GIT_BRANCH: "main"
        GIT_HASH: "a99c738bc395c5e0871b1d289d3a387d41bf24ad"
      casbin:
        GIT_BRANCH: "main"
        GIT_HASH: "a99c738bc395c5e0871b1d289d3a387d41bf24ad"
