installer:
  release: "v0.4.18"
  image: "quay.io/devtron/inception"
  tag: "c62d4c30-185-9354"
  
components:
  dashboard:
    image: "quay.io/devtron/dashboard:7141e4b4-325-9438"
  devtron:
    image: "quay.io/devtron/hyperion:749548dd-280-9429"
    cicdImage: "quay.io/devtron/devtron:749548dd-326-9433"
  argocdDexServer:
    image: "quay.io/dexidp/dex:v2.25.0"
    initContainer:
      authenticator: "quay.io/devtron/authenticator:415f5470-279-6520"
      cicdAuthenticator: "quay.io/argoproj/argocd:v1.8.1"
  kubelink:
    image: "quay.io/devtron/kubelink:59a0df88-318-9226"
  postgres:
    image: "quay.io/devtron/postgres:11.9.0-debian-10-r26"
  
  migrator:
    image: "quay.io/devtron/migrator:6687f572-133-2208"
    envVars:
      devtron:
        GIT_BRANCH: "main"
        GIT_HASH: "749548dd22e8ca5ad478541924e499d325cd00c9"
      casbin:
        GIT_BRANCH: "main"
        GIT_HASH: "749548dd22e8ca5ad478541924e499d325cd00c9"
