installer:
  release: "v0.4.12"
  image: "quay.io/devtron/inception"
  tag: "acb623ff-185-7117"
  
components:
  dashboard:
    image: "quay.io/devtron/dashboard:5ff53a9a-240-9140"
  devtron:
    image: "quay.io/devtron/hyperion:8b954d75-280-9142"
    cicdImage: "quay.io/devtron/devtron:8b954d75-324-9141"
  argocdDexServer:
    image: "quay.io/dexidp/dex:v2.25.0"
    initContainer:
      authenticator: "quay.io/devtron/authenticator:415f5470-279-6520"
      cicdAuthenticator: "quay.io/argoproj/argocd:v1.8.1"
  kubelink:
    image: "quay.io/devtron/kubelink:d691bfbb-318-8695"
  postgres:
    image: "quay.io/devtron/postgres:11.9.0-debian-10-r26"
  
  migrator:
    image: "quay.io/devtron/migrator:6687f572-133-2208"
    envVars:
      devtron:
        GIT_BRANCH: "main"
        GIT_HASH: "8b954d75d44f89cab11327026de2b70e4818c26e"
      casbin:
        GIT_BRANCH: "main"
        GIT_HASH: "8b954d75d44f89cab11327026de2b70e4818c26e"
