installer:
  release: "v0.4.5"
  image: "quay.io/devtron/inception"
  tag: "acb623ff-185-7117"
  
components:
  dashboard:
    image: "quay.io/devtron/dashboard:8c3c47c8-240-8803"
  devtron:
    image: "quay.io/devtron/hyperion:702ffd2c-280-8805"
  argocdDexServer:
    image: "quay.io/dexidp/dex:v2.25.0"
  kubelink:
    image: "quay.io/devtron/kubelink:d691bfbb-318-8695"
  postgres:
    image: "quay.io/devtron/postgres:11.9.0-debian-10-r26"
  
  migrator:
    image: "quay.io/devtron/migrator:6687f572-133-2208"
    envVars:
      devtron:
        GIT_BRANCH: "main"
        GIT_HASH: "702ffd2c7814e33f49e0dbbbebc6e18a6645e5d3"
      casbin:
        GIT_BRANCH: "main"
        GIT_HASH: "702ffd2c7814e33f49e0dbbbebc6e18a6645e5d3"
